### ISSUE TITLE
ImportError: No module named json

### ISSUE THREAD

**Issue by mimoccc** [kalliope-project/kalliope_starter_cs#3]
ImportError: No module named json after start

**Comment by mimoccc** [comment]
mimo@mimo-laptop-2:~/Desktop/kalliope_starter_cs-master$ kalliope start
Traceback (most recent call last):
  File "/usr/local/bin/kalliope", line 11, in <module>
    load_entry_point('kalliope==0.5.5', 'console_scripts', 'kalliope')()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2852, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python2.7/dist-packages/kalliope-0.5.5-py2.7.egg/kalliope/__init__.py", line 12, in <module>
    from flask import Flask
  File "/usr/local/lib/python2.7/dist-packages/Flask-1.1.1-py2.7.egg/flask/__init__.py", line 21, in <module>
    from .app import Flask
  File "/usr/local/lib/python2.7/dist-packages/Flask-1.1.1-py2.7.egg/flask/app.py", line 69, in <module>
    from .wrappers import Request
  File "/usr/local/lib/python2.7/dist-packages/Flask-1.1.1-py2.7.egg/flask/wrappers.py", line 14, in <module>
    from werkzeug.wrappers.json import JSONMixin as _JSONMixin
ImportError: No module named json
mimo@mimo-laptop-2:~/Desktop/kalliope_starter_cs-master$

**Comment by Sispheor** [comment]
If you have installed kalliope you should have json installed.
Try sudo pip install json.

**Comment by mimoccc** [comment]
pip list --outdated --format=freeze | grep -v '^\-e' | cut -d = -f 1  | xargs -n1 pip install -U

**Comment by Sispheor** [comment]
Json is not declared in the setup but I think it's installed by flask.

**Comment by mimoccc** [comment]
yes, thats right. i have to update packages manually as i wrote in comment.
thanx

**Comment by mimoccc** [comment]
actualy, this is an issue of installer, it should check & update, if
possible, pip packages, before start...

**Comment by Sispheor** [comment]
The installer calls the setup.py which contains all required lib and dependencies. So it should be ok. How did you install?

**Comment by mimoccc** [comment]
install bash script.
