### ISSUE TITLE
after installation & dependencies manual check still not working

### ISSUE THREAD

**Issue by mimoccc** [kalliope-project/kalliope_starter_cs#4]
It hangs on invitation sentence, on both en, and cs languages.

**cs error:**
Exception in thread <class 'kalliope.signals.order.order.Order'>:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/local/lib/python2.7/dist-packages/kalliope-0.5.5-py2.7.egg/kalliope/signals/order/order.py", line 87, in run
    self.start_trigger()
  File "/usr/local/lib/python2.7/dist-packages/transitions-0.7.1-py2.7.egg/transitions/core.py", line 405, in trigger
    return self.machine._process(func)
  File "/usr/local/lib/python2.7/dist-packages/transitions-0.7.1-py2.7.egg/transitions/core.py", line 1086, in _process
    self._transition_queue[0]()
  File "/usr/local/lib/python2.7/dist-packages/transitions-0.7.1-py2.7.egg/transitions/core.py", line 423, in _trigger
    return self._process(event_data)
  File "/usr/local/lib/python2.7/dist-packages/transitions-0.7.1-py2.7.egg/transitions/core.py", line 433, in _process
    if trans.execute(event_data):
  File "/usr/local/lib/python2.7/dist-packages/transitions-0.7.1-py2.7.egg/transitions/core.py", line 283, in execute
    self._change_state(event_data)
  File "/usr/local/lib/python2.7/dist-packages/transitions-0.7.1-py2.7.egg/transitions/core.py", line 294, in _change_state
    event_data.machine.get_state(self.dest).enter(event_data)
  File "/usr/local/lib/python2.7/dist-packages/transitions-0.7.1-py2.7.egg/transitions/core.py", line 140, in enter
    event_data.machine.callback(handle, event_data)
  File "/usr/local/lib/python2.7/dist-packages/transitions-0.7.1-py2.7.egg/transitions/core.py", line 1031, in callback
    func(*event_data.args, **event_data.kwargs)
  File "/usr/local/lib/python2.7/dist-packages/kalliope-0.5.5-py2.7.egg/kalliope/signals/order/order.py", line 97, in start_trigger_process
    self.trigger_instance.daemon = True
AttributeError: 'NoneType' object has no attribute 'daemon'

**en warnings:**
/usr/local/lib/python2.7/dist-packages/cffi-1.13.2-py2.7-linux-x86_64.egg/cffi/cparser.py:164: UserWarning: Global variable 'stderr' in cdef(): for consistency with C it should have a storage class specifier (usually 'extern')
  "(usually 'extern')" % (decl.name,))
/usr/local/lib/python2.7/dist-packages/cffi-1.13.2-py2.7-linux-x86_64.egg/cffi/cparser.py:164: UserWarning: Global variable '__stderrp' in cdef(): for consistency with C it should have a storage class specifier (usually 'extern')
  "(usually 'extern')" % (decl.name,))

No hotword detection work.

**Comment by Sispheor** [comment]
Past your settings here please

**Comment by mimoccc** [comment]
i use settings from preconfigured packages cs and en

**Comment by mimoccc** [comment]
never mind.
i just leave your project.
please focus on self installation scripts.
and dependencies check.
i end on that my microphone is not on right sampling range.
just i realy recommend you to use deepspeech from mozilla. it does not need
any api key and works amazing compare to another stt engines.
i am playing with now, and discover it as most easiest to integrate, it
works with almost any language, there is about 22 languages recognizable
and grooving. and you can made it out of cloud.

br

milan

Dňa st 20. 11. 2019, 17:56 milan <notifications@github.com> napísal(a):

**Comment by Sispheor** [comment]
Ok ok. Sorry that you had some issues. I used the script for my own install and for creating the pre compiled image without any trouble.
And we haven't had any wrong feedback about it so far on the main repo. Don't hesitate to come on the gitter chat anytime.
++

**Comment by mimoccc** [comment]
no, no, i am happy that i found your project,we are going the same way :),
i wish to made my own, and possible out of cloud solution for home
assistant.
the problem is only with installation & configuration of packages.
i also try mycroft, and there you can find solution for the sample rate
problem, and it is happen in packages you are not mantainer of.
keep going man.
i am slovakian, and your project is only one, who accepts and supports
languages other than spanish, english, and etc.
thats why i was happy to meet kalliope.
just after couple of hours to get it work, i still keep android system as a
base and will continue my own project.
please try to use deepspeech, it is easy to use and can help your project.
i am very satisfied with deepspeech so far.
wish you br.

m


Dňa st 27. 11. 2019, 7:33 Nicolas Marcq <notifications@github.com>
napísal(a):

**Comment by Sispheor** [comment]
Kalliope already support offline stt and tts.
Deepspech will be implemented soon.
And there is a sample rate feature for the trigger also.
Have fun with your project then.
